#!/usr/bin/env node

/**
 * Stripe Setup Helper Script
 * This script helps you create the .env.local file for Stripe configuration
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setupStripe() {
  console.log('\n🎬 Stripe Setup for AnimeFlix\n');
  console.log('This will help you create a .env.local file with your Stripe keys.\n');
  console.log('If you don\'t have Stripe keys yet:');
  console.log('1. Go to https://dashboard.stripe.com/test/apikeys');
  console.log('2. Copy your Publishable key (pk_test_...)');
  console.log('3. Click "Reveal" and copy your Secret key (sk_test_...)\n');

  const publishableKey = await question('Enter your Stripe Publishable Key (pk_test_...): ');
  const secretKey = await question('Enter your Stripe Secret Key (sk_test_...): ');
  const monthlyPriceId = await question('Enter Monthly Price ID (price_...) [or press Enter to skip]: ');
  const annualPriceId = await question('Enter Annual Price ID (price_...) [or press Enter to skip]: ');
  const baseUrl = await question('Enter Base URL [default: http://localhost:3000]: ') || 'http://localhost:3000';

  const envContent = `# Stripe Configuration
# Generated by setup-stripe.js

NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${publishableKey}
STRIPE_SECRET_KEY=${secretKey}
${monthlyPriceId ? `NEXT_PUBLIC_STRIPE_PRICE_ID=${monthlyPriceId}` : '# NEXT_PUBLIC_STRIPE_PRICE_ID=price_your_monthly_price_id'}
${annualPriceId ? `NEXT_PUBLIC_STRIPE_ANNUAL_PRICE_ID=${annualPriceId}` : '# NEXT_PUBLIC_STRIPE_ANNUAL_PRICE_ID=price_your_annual_price_id'}
NEXT_PUBLIC_BASE_URL=${baseUrl}

# Optional: Webhook Secret (for production)
# STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here
`;

  const envPath = path.join(process.cwd(), '.env.local');
  
  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ Successfully created .env.local file!');
    console.log('\n📝 Next steps:');
    console.log('1. Create products in Stripe Dashboard: https://dashboard.stripe.com/test/products');
    console.log('2. Copy the Price IDs and add them to .env.local');
    console.log('3. Restart your dev server: npm run dev');
    console.log('\n🎉 Stripe is now configured!\n');
  } catch (error) {
    console.error('\n❌ Error creating .env.local:', error.message);
  }

  rl.close();
}

setupStripe();

